Repository team-mirai/policy, pull requests merged in 2025-06, with the labels that each got.

#77 表現の微修正
  02_政策インデックス.md
  30_ステップ３「長期の成長に大胆に投資する」.md
  31_ステップ３子育て.md
  32_ステップ３教育.md
Labels: 教育, 子育て

#1875 Update 33_ステップ３科学技術.md
  33_ステップ３科学技術.md
Labels: 科学技術

#1873 Update 33_ステップ３科学技術.md
  33_ステップ３科学技術.md
Labels: 科学技術

#1982 Update step3 section1
  32_ステップ３教育.md
Labels: 教育

#1983 Update step3 section2
  32_ステップ３教育.md
Labels: 教育

#1975 Update Step1 - Vision & Section1
  11_ステップ１教育.md
Labels: 教育

#1976 Update Step1 / Section2
  11_ステップ１教育.md
Labels: 教育

#1977 Update Step1 / Section3
  11_ステップ１教育.md
Labels: 教育

#1979 Update Step2 / Section1
  21_ステップ２教育.md
Labels: 教育

#1980 Update step2 / section2
  21_ステップ２教育.md
Labels: 教育

#1978 Update Step1 / Section 4,5,6
  11_ステップ１教育.md
Labels: 教育

#1997 Update 17_ステップ１医療.md
  17_ステップ１医療.md
Labels: 医療

#1964 Add files via upload　ステップ２デジタル民主主義を追加
  .github/.linkspector.yml
  15_ステップ１科学技術.md
  22_ステップ２行政改革.md
  25_ステップ２_デジタル民主主義.md
Labels: [システム], 行政改革, 科学技術, デジタル民主主義

#2266 日本の科学技術の課題（論文数などの国際比較）
  15_ステップ１科学技術.md
Labels: 科学技術

#2247 GitHubで行われているマニフェストのアップデートを、X(旧Twitter)でお知らせする機能の実装
  .github/scripts/post_to_x.ts
  .github/workflows/post-to-x.yml
Labels: [システム]

#2353 31_ステップ３子育て_「子育て減税」の導入.md
  31_ステップ３子育て.md
Labels: 子育て

#2366 運営費交付金のアップデートを通じた基盤的な研究・研究者の雇用の安定
  33_ステップ３科学技術.md
Labels: 科学技術

#2953 科学技術を通じて実現するビジョンの修正　Update 33_ステップ３科学技術.md
  33_ステップ３科学技術.md
Labels: 科学技術

#2916 Update 16_ステップ１デジタル民主主義.md
  16_ステップ１デジタル民主主義.md
Labels: デジタル民主主義

#2970 Fix markdown link syntax error in 31_ステップ３子育て.md
  .github/markdown-link-check-config.json
  .github/workflows/markdown-link-check.yml
  .gitignore
  16_ステップ１デジタル民主主義.md
  31_ステップ３子育て.md
Labels: 子育て
