Repository team-mirai/policy, pull requests merged in 2025-07, with the labels that each got.

#3204 フリーランスの方向けの育児休業給付
  31_ステップ３子育て.md
Labels: 子育て

#3118 体験学習クーポンについての記述詳細化
  32_ステップ３教育.md
Labels: 教育

#3049 14_ステップ１産業の更新
  14_ステップ１産業.md
Labels: 産業政策

#3791 マニフェストの順位の件追加
  01_チームみらいのビジョン.md
Labels: ビジョン

#6315 ステップ３子育て政策をインパクト順に並び替え
  02_政策インデックス.md
  31_ステップ３子育て.md
Labels: skip-notification

#6325 多胎児育児に関する課題への対応策を追加.md
  12_ステップ１子育て.md
Labels: 子育て

#6353 ReadMeの目次の微修正
  23_ステップ２医療.md
  24_ステップ２デジタル民主主義.md
  25_ステップ２福祉.md
  README.md
Labels: skip-notification

#6718 誤字修正、「障害」表記への統一
  31_ステップ３子育て.md
Labels: skip-notification

#6505 博士課程の学生に対する政策を大幅に拡充
  33_ステップ３科学技術.md
Labels: 科学技術
